
PATCH http://localhost:8080/users/a1b1
content-type: application/json

{
   
"favorites" : [8, 12]
}

###
GET http://localhost:8080/users/I2sid61150S3vy0kKwRmv2lBkHM2

###
POST   http://localhost:8080/users
content-type: application/json

{

"favorites" : [],
"localId" : "134343434",
}

###